export const jobListings = [
    {
      href: "/jobs/junior-graphic-designer",
      title: "Junior Graphic Designer (Web)",
      companyLogo: "/job-logo.jpg",
      companyName: "Design Co.",
      categories: ["Design", "Development"],
      location: "New York",
      employmentType: "Full Time",
      isFeatured: true,
      isUrgent: true,
      salaryRange: "$150 - $180 / week",
    },
    {
      href: "/jobs/finance-manager-health",
      title: "Finance Manager & Health",
      companyLogo: "/job-logo.jpg",
      companyName: "Finance Group",
      categories: ["Design"],
      location: "New York",
      employmentType: "Full Time",
      isFeatured: true,
      isUrgent: true,
      salaryRange: "$450 - $500 / month",
    },
    {
      href: "/jobs/general-ledger-accountant",
      title: "General Ledger Accountant",
      companyLogo: "/job-logo.jpg",
      companyName: "Upwork",
      categories: ["Design", "Marketing"],
      location: "New York",
      employmentType: "Full Time",
      isFeatured: true,
      isUrgent: false,
      salaryRange: "$50 - $68 / day",
    },
    {
      href: "/jobs/assistant-store-keeper",
      title: "Assistant / Store Keeper",
      companyLogo: "/job-logo.jpg",
      companyName: "Netflix",
      categories: ["Automotive Jobs", "Marketing"],
      location: "New York",
      employmentType: "Part Time",
      isFeatured: true,
      isUrgent: false,
      salaryRange: "$250 - $280 / week",
    },
    {
      href: "/jobs/group-marketing-manager",
      title: "Group Marketing Manager",
      companyLogo: "/job-logo.jpg",
      companyName: "Marketing Inc.",
      categories: ["Customer", "Marketing"],
      location: "Miami",
      employmentType: "Part Time",
      isFeatured: false,
      isUrgent: false,
      salaryRange: "$800 - $850 / month",
    },
    {
      href: "/jobs/product-sales-specialist",
      title: "Product Sales Specialist",
      companyLogo: "/job-logo.jpg",
      companyName: "Sales Experts",
      categories: ["Project Management"],
      location: "New York",
      employmentType: "Internship",
      isFeatured: true,
      isUrgent: false,
      salaryRange: "$520 - $650 / month",
    },
  ];
  